version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=TestCoursework
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: TestCoursework
